# Generated by Django 4.2.3 on 2023-07-17 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_coursedatatheme_subcategory_alter_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='registercourseuser',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursethemecomment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Course/theme/comment'),
        ),
        migrations.AlterField(
            model_name='registercourseuser',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registercourse', to='course.course'),
        ),
    ]
