# Generated by Django 4.2.3 on 2023-07-27 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_remove_course_user_course_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registercourseuser',
            name='completed_themes',
            field=models.ManyToManyField(blank=True, to='course.coursedatatheme'),
        ),
    ]
