# Generated by Django 4.2.3 on 2023-07-25 02:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lesson', '0002_remove_lessonrequest_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='attended_students',
            field=models.ManyToManyField(blank=True, related_name='attended_students', to=settings.AUTH_USER_MODEL),
        ),
    ]
