# Generated by Django 4.2.3 on 2023-07-25 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_alter_education_students_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='education',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lesson.education'),
            preserve_default=False,
        ),
    ]
