# Generated by Django 4.2.3 on 2023-07-25 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0004_lesson_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='education',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='lesson.education'),
        ),
    ]
